name: DocFX Build
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      # Check out the branch that triggered this workflow to the 'source' subdirectory
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          path: source
      # Check out gh-pages branch to the 'docs' subdirectory
      - name: Checkout docs
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: docs
      # Run a build
      - name: Build docs
        run: "& ./eng/common/build.ps1 -restore -build -projects ./docs/docfx/docfx.csproj"
        working-directory: ./source
      # Show the site
      - name: Show site dir
        run: dir ./source/docs/docfx/_site
      # Clear the content of the docs repo, since we're going to lay down new content and want old stuff removed
      - name: Clear docs repo
        run: Remove-Item -Recurse -Force ./docs/* -Exclude .git
      # Copy to the docs repo
      - name: Copy to docs repo
        run: Copy-Item -Recurse -Force ./source/docs/docfx/_site/* ./docs
      # Show the copied site
      - name: Show site dir
        run: dir ./docs

