name: DocFX Build
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      # Check out the branch that triggered this workflow to the 'source' subdirectory
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          path: source
      # Check out gh-pages branch to the 'docs' subdirectory
      - name: Checkout docs
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: docs
      # Run a build
      - name: Build docs
        run: "& ./eng/common/build.ps1 -restore -build -projects ./docs/docfx/docfx.csproj"
        working-directory: ./source
      # Show the site
      - name: Show site dir
        run: dir ./docs/docsfx/_site
        working-directory: ./source

