name: DocFX Build
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      # Check out the branch that triggered this workflow to the 'source' subdirectory
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          path: source
      # Run a build
      - name: Build docs
        run: "& ./eng/common/build.ps1 -restore -build -projects ./docs/docfx/docfx.csproj"
        working-directory: ./source
      # Check out gh-pages branch to the 'docs' subdirectory
      - name: Checkout docs
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: docs
      # Sync the site
      - name: Clear docs repo
        run: Get-ChildItem -Force -Exclude .git | ForEach-Object { Remove-Item -Recurse -Verbose -Force $_ }
        working-directory: ./docs
      - name: Sync new content
        run: Copy-Item -Recurse -Verbose -Force "$env:GITHUB_WORKSPACE/source/docs/docfx/_site/*" .
        working-directory: ./docs
      # Check if there are actually changes (commit will fail if there aren't)
      - name: Check for changes
        id: git-check
        run: |
          $ErrorActionPreference = "Continue"
          git diff-index --quiet HEAD --
          if ($LASTEXITCODE -eq 0) {
            echo "::set-output name=modified:true"
          } else {
            echo "::set-output name=modified:false"
          }
        working-directory: ./docs
      # Commit
      - name: Commit to gh-pages and push
        if: steps.git-check.outputs.modified == 'true'
        run: |
          cd "$env:GITHUB_WORKSPACE/docs"
          git add -A
          git config --global user.name "$env:GITHUB_ACTOR (via Actions)"
          git config --global user.email "$env:GITHUB_ACTOR@users.noreply.github.com"
          git commit -m"Updated docs from commit $env:GITHUB_SHA on $env:GITHUB_REF"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin gh-pages
        working-directory: ./docs